services:

  thomas-poc:
    image: thomas-poc:0.1.0
    build:
      dockerfile: Dockerfile
      tags:
        - thomas-poc:0.1.0
    container_name: thomas-poc
    environment:
      WHISPER_MODEL_DIRECTORY: /app/whisper/
      INPUT_DIRECTORY: /input
      OUTPUT_DIRECTORY: /output
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    volumes:
      - ./models:/app/whisper/
      - ./input:/input
      - ./output:/output
