services:

  thomas-poc:
    build: .
    container_name: thomas-poc
    environment:
      WHISPER_MODEL_DIRECTORY: /app/whisper/
      INPUT_DIRECTORY: /input
      OUTPUT_DIRECTORY: /output
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    volumes:
      - ./models:/app/whisper/
      - ./input:/input
      - ./output:/output
